"""
Django settings for medical_job_portal project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*fol_f(c%wk3oe)&a9xb8gad*7#wv2#_&ho6&g=8azoa$k(!@%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'doctors',
    'nurses',
    'hospitals',
    'admin_panel',
    'shifts',
    'plans'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'medical_job_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'plans.context_processors.plan_permissions',
            ],
        },
    },
]

WSGI_APPLICATION = 'medical_job_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

STATIC_URL = '/static/'

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CustomUser model use karna hai
AUTH_USER_MODEL = 'users.CustomUser'
 
# Login/logout redirect
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
X_FRAME_OPTIONS = 'SAMEORIGIN'

SESSION_COOKIE_AGE = 6000       # 10 min baad session expire
SESSION_EXPIRE_AT_BROWSER_CLOSE = True   # browser band = session khatam


RAZORPAY_KEY_ID     = 'rzp_test_SdlnnROArhiIau'
RAZORPAY_KEY_SECRET = 'oJTH7ieb62e5OLlgrVhwBgfJ'

# SMS Config
MSGCLUB_AUTH_KEY  = "c2921f7ddbcf56e41987a5ed7d82a47"
MSGCLUB_SENDER_ID = "PROLCM"

# Template IDs
MSGCLUB_TEMPLATE_LOGIN                  = "1707177850102781169"
MSGCLUB_TEMPLATE_SIGNUP                 = "1707177850190790817"
MSGCLUB_TEMPLATE_FORGOT                 = "1707177850198710314"
MSGCLUB_TEMPLATE_ACCOUNT_VERIFIED       = "1707177850264877202"
MSGCLUB_TEMPLATE_WELCOME                = "1707177867746116635"
MSGCLUB_TEMPLATE_APP_NOT_SELECTED       = "1707177867772845820"
MSGCLUB_TEMPLATE_APP_SUBMITTED          = "1707177867775499145"
MSGCLUB_TEMPLATE_APP_ACCEPTED           = "1707177867777213503"
MSGCLUB_TEMPLATE_EMERGENCY              = "1707177867784455813"
MSGCLUB_TEMPLATE_SHIFT_CONFIRMATION     = "1707177851161159834"
MSGCLUB_TEMPLATE_SHIFT_REMINDER         = "1707177851170244812"
MSGCLUB_TEMPLATE_SHIFT_START_OTP        = "1707177851198333860"
MSGCLUB_TEMPLATE_SHIFT_COMPLETED        = "1707177851205933733"
MSGCLUB_TEMPLATE_PAYMENT_PAID           = "1707177851214762359"
MSGCLUB_TEMPLATE_PASSWORD_RESET_SUCCESS = "1707177851219892258"
MSGCLUB_TEMPLATE_NEW_SHIFT              = "1707178077573609959"