# Generated by Django 5.2.1 on 2026-04-19 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFreeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('hospital', 'Hospital')], max_length=20, unique=True)),
                ('free_tokens', models.PositiveIntegerField(default=0, help_text='Doctor/Nurse ko free tokens')),
                ('free_vacancy_limit', models.PositiveIntegerField(default=0, help_text='Doctor/Nurse ko free vacancy apply limit')),
                ('free_shift_post_limit', models.PositiveIntegerField(default=0, help_text='Hospital ko free shift post limit')),
                ('free_vacancy_post_limit', models.PositiveIntegerField(default=0, help_text='Hospital ko free vacancy post limit')),
            ],
            options={
                'verbose_name': 'Default Free Credit Setting',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('hospital', 'Hospital')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tokens', models.PositiveIntegerField(default=0, help_text='Kitne tokens milenge (shift apply ke liye)')),
                ('vacancy_limit', models.PositiveIntegerField(default=0, help_text='Kitni vacancies pe apply kar sakta hai')),
                ('shift_post_limit', models.PositiveIntegerField(default=0, help_text='Kitne shifts post kar sakta hai')),
                ('vacancy_post_limit', models.PositiveIntegerField(default=0, help_text='Kitni vacancies post kar sakta hai')),
            ],
            options={
                'ordering': ['role', 'price'],
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('bought_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy_limit_used', models.PositiveIntegerField(default=0)),
                ('shift_post_used', models.PositiveIntegerField(default=0)),
                ('vacancy_post_used', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bought_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='plans.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
