# Generated by Django 5.2.1 on 2026-05-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultfreecredit',
            name='free_duration_months',
            field=models.PositiveIntegerField(default=1, help_text='Free plan kitne mahine ka hoga'),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveIntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months (1 Year)')], default=1, help_text='Plan kitne mahine ka hai'),
        ),
        migrations.AddField(
            model_name='plan',
            name='unlimited_shift_post',
            field=models.BooleanField(default=False, help_text='Unlimited shift post?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='unlimited_tokens',
            field=models.BooleanField(default=False, help_text='Unlimited tokens?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='unlimited_vacancy_apply',
            field=models.BooleanField(default=False, help_text='Unlimited vacancy apply?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='unlimited_vacancy_post',
            field=models.BooleanField(default=False, help_text='Unlimited vacancy post?'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defaultfreecredit',
            name='free_shift_post_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defaultfreecredit',
            name='free_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defaultfreecredit',
            name='free_vacancy_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defaultfreecredit',
            name='free_vacancy_post_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tokens',
            field=models.PositiveIntegerField(default=0, help_text='Tokens milenge (shift apply ke liye)'),
        ),
    ]
