# Generated by Django 5.2.1 on 2026-05-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_defaultfreecredit_free_duration_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='unlimited_tokens',
        ),
        migrations.AddField(
            model_name='defaultfreecredit',
            name='free_is_lifetime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_lifetime',
            field=models.BooleanField(default=False, help_text='Check karo agar plan kabhi expire na ho (Lifetime)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='shift_post_enabled',
            field=models.BooleanField(default=False, help_text='Kya is plan mein shift posting feature ON hai?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='token_mode',
            field=models.CharField(choices=[('disabled', 'No Tokens'), ('fixed', 'Fixed Amount'), ('unlimited', 'Unlimited')], default='disabled', help_text='disabled=tokens nahi, fixed=X tokens, unlimited=∞ tokens', max_length=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='vacancy_apply_enabled',
            field=models.BooleanField(default=False, help_text='Kya is plan mein vacancy apply feature ON hai?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='vacancy_post_enabled',
            field=models.BooleanField(default=False, help_text='Kya is plan mein vacancy posting feature ON hai?'),
        ),
        migrations.AlterField(
            model_name='defaultfreecredit',
            name='free_duration_months',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveIntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months (1 Year)')], default=1, help_text='Plan kitne mahine ka hai (is_lifetime=False hone par kaam aata hai)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='shift_post_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tokens',
            field=models.PositiveIntegerField(default=0, help_text="Sirf token_mode='fixed' hone par use hota hai"),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unlimited_shift_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unlimited_vacancy_apply',
            field=models.BooleanField(default=False, help_text='Unlimited vacancy apply? (vacancy_apply_enabled=True hona chahiye)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='unlimited_vacancy_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vacancy_limit',
            field=models.PositiveIntegerField(default=0, help_text='Kitni vacancies pe apply kar sakta hai (unlimited_vacancy_apply=False hone par)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='vacancy_post_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
