# Generated by Django 5.2.1 on 2026-05-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_remove_plan_unlimited_tokens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '12 Months (1 Year)')], default=1, help_text='Plan kitne mahine ka hai (is_lifetime=False hone par kaam aata hai)', null=True),
        ),
    ]
