# Generated by Django 5.2.1 on 2026-05-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='shift_view_enabled',
            field=models.BooleanField(default=False, help_text='Kya is plan mein Available Shifts dekhne ki permission hai?'),
        ),
    ]
