# Generated by Django 5.2.1 on 2026-05-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_plan_shift_view_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='urgent_shift_enabled',
            field=models.BooleanField(default=False, help_text='Dashboard pe urgent shifts dikhenge (shift_view_enabled bhi hona chahiye)'),
        ),
    ]
