# Generated by Django 5.2.1 on 2026-06-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_plan_urgent_shift_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='urgent_shift_post_enabled',
            field=models.BooleanField(default=False, help_text='Kya is plan mein urgent shift post karne ki permission hai?'),
        ),
    ]
