# Generated by Django 5.2.1 on 2026-04-10 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('ward_type', models.CharField(choices=[('general', 'General Ward'), ('icu', 'ICU Ward'), ('casualty', 'Casualty Ward'), ('female', 'Female Ward')], max_length=20)),
                ('bed_count', models.PositiveIntegerField(default=1)),
                ('address', models.TextField()),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('qualification_required', models.CharField(choices=[('mbbs', 'MBBS'), ('bams', 'BAMS'), ('bhms', 'BHMS'), ('bams_bhms', 'BAMS/BHMS')], default='bams_bhms', max_length=20)),
                ('shift_type', models.CharField(choices=[('single', 'Single Shift'), ('multiple', 'Multiple Shift')], default='single', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pay', models.PositiveIntegerField(help_text='Pay in INR')),
                ('requirements', models.TextField(blank=True, help_text='e.g. Carry ID Card, Reach 15 min before')),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_applications', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='shifts.shift')),
            ],
            options={
                'unique_together': {('shift', 'applicant')},
            },
        ),
    ]
