# Generated by Django 5.2.1 on 2026-04-12 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftapplication',
            name='onboard_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('onboarded', 'Onboarded'), ('arrived', 'Arrived'), ('started', 'Started'), ('completed', 'Completed')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='shift',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shiftapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('reserved', 'Reserved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=15),
        ),
        migrations.CreateModel(
            name='ShiftReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_type', models.CharField(choices=[('doctor', 'Doctor → Hospital'), ('hospital', 'Hospital → Doctor')], max_length=10)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shifts.shiftapplication')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('application', 'reviewer_type')},
            },
        ),
    ]
