# Generated by Django 5.2.1 on 2026-04-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shiftapplication_onboard_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='target_role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
