# Generated by Django 5.2.1 on 2026-05-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shift_target_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='qualification_required',
            field=models.CharField(choices=[('mbbs', 'MBBS'), ('bams', 'BAMS'), ('bhms', 'BHMS'), ('bams_bhms', 'BAMS/BHMS'), ('gnm', 'GNM'), ('bsc_nursing', 'B.Sc Nursing'), ('anm', 'ANM'), ('msc_nursing', 'M.Sc Nursing')], default='bams_bhms', max_length=20),
        ),
    ]
