# Generated by Django 5.2.1 on 2026-05-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_alter_shift_qualification_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='target_role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], default='both', max_length=10),
        ),
    ]
