# Generated by Django 5.2.1 on 2026-05-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0005_alter_shift_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='location_link',
            field=models.URLField(blank=True, help_text='Google Maps link', null=True),
        ),
    ]
