# Generated by Django 5.2.1 on 2026-05-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_shift_location_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='location_link',
            field=models.URLField(blank=True, help_text='Google Maps link', max_length=500, null=True),
        ),
    ]
