# Generated by Django 5.2.1 on 2026-06-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_alter_shift_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftapplication',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
