# Generated by Django 5.2.1 on 2026-06-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_shiftapplication_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftapplication',
            name='hospital_marked_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftapplication',
            name='hospital_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shiftapplication',
            name='locum_confirmed_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shiftapplication',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('upi', 'UPI'), ('cash', 'Cash')], max_length=10),
        ),
        migrations.AddField(
            model_name='shiftapplication',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('disputed', 'Disputed')], default='unpaid', max_length=10),
        ),
    ]
