# Generated by Django 5.2.1 on 2026-04-12 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospitalprofile_verification_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('staff_type', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('both', 'Both')], default='doctor', max_length=10)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('ward_type', models.CharField(blank=True, choices=[('general', 'General Ward'), ('icu', 'ICU Ward'), ('casualty', 'Casualty Ward'), ('female', 'Female Ward'), ('pediatric', 'Pediatric Ward'), ('maternity', 'Maternity Ward')], max_length=20)),
                ('bed_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('doctor_qualification', models.CharField(blank=True, choices=[('mbbs', 'MBBS'), ('bams', 'BAMS'), ('bhms', 'BHMS')], max_length=10)),
                ('nurse_qualification', models.CharField(blank=True, choices=[('gnm', 'GNM'), ('bsc_nursing', 'B.Sc Nursing'), ('anm', 'ANM'), ('msc_nursing', 'M.Sc Nursing')], max_length=20)),
                ('experience_required', models.CharField(blank=True, max_length=100)),
                ('shift_type', models.CharField(choices=[('single', 'Single Shift'), ('multiple', 'Multiple Shift')], default='single', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=15)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_applications', to=settings.AUTH_USER_MODEL)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hospitals.vacancy')),
            ],
            options={
                'unique_together': {('vacancy', 'applicant')},
            },
        ),
    ]
