# Generated by Django 5.2.1 on 2026-05-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_vacancy_vacancyapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='staff_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse')], default='doctor', max_length=10),
        ),
    ]
