# Generated by Django 5.2.1 on 2026-05-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_alter_vacancy_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='shift_label',
            field=models.CharField(blank=True, choices=[('morning', 'Morning Shift'), ('evening', 'Evening Shift'), ('night', 'Night Shift'), ('rotational', 'Rotational Shift')], default='', max_length=15),
        ),
    ]
