# Generated by Django 5.2.1 on 2026-06-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_vacancy_shift_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
