# Generated by Django 5.2.1 on 2026-06-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_alter_vacancy_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='aadhar_photo',
            field=models.FileField(blank=True, null=True, upload_to='hospitals/aadhar/'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='hospitals/pan/'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='registration_doc',
            field=models.FileField(blank=True, null=True, upload_to='hospitals/docs/'),
        ),
    ]
