# Generated by Django 5.2.1 on 2026-06-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_hospitalprofile_aadhar_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='doctor_qualification',
            field=models.CharField(blank=True, choices=[('mbbs', 'MBBS'), ('bams', 'BAMS'), ('bhms', 'BHMS'), ('bams_bhms', 'BAMS/BHMS')], max_length=30),
        ),
    ]
