# Generated by Django 5.2.1 on 2026-04-08 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('registration_no', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, choices=[('mbbs', 'MBBS'), ('bams', 'BAMS'), ('bhms', 'BHMS')], max_length=10)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('ward_preferences', models.CharField(blank=True, max_length=200)),
                ('known_procedures', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/')),
                ('aadhar_photo', models.ImageField(blank=True, null=True, upload_to='doctors/aadhar/')),
                ('pan_card', models.ImageField(blank=True, null=True, upload_to='doctors/pan/')),
                ('degree_photo', models.ImageField(blank=True, null=True, upload_to='doctors/degree/')),
                ('registered_state', models.CharField(blank=True, max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
