# Generated by Django 5.2.1 on 2026-04-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_registration_complete',
            field=models.BooleanField(default=False),
        ),
    ]
