# Generated by Django 5.2.1 on 2026-06-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
